module.exports = {
	plugins: [require.resolve("prettier-plugin-pkg")],
	arrowParens: "always",
	bracketSameLine: false,
	bracketSpacing: false,
	endOfLine: "lf",
	htmlWhitespaceSensitivity: "css",
	jsxSingleQuote: false,
	printWidth: 100,
	proseWrap: "preserve",
	quoteProps: "as-needed",
	semi: true,
	singleQuote: false,
	tabWidth: 1,
	trailingComma: "all",
	useTabs: true,
};
