services:
  db:
    image: mariadb
    mem_limit: 2048m
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:6-fpm-alpine
    depends_on:
      - db
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: "${MYSQL_DATABASE}"
      WORDPRESS_DB_USER: "${MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
      WORDPRESS_BASE_URL: "${WORDPRESS_BASE_URL}"
      WORDPRESS_DEBUG: true
      NEXT_BASE_URL: "${NEXT_BASE_URL}"
      JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
      DATA_TOKEN: "${DATA_TOKEN}"
    volumes:
      - ./wordpress:/var/www/html
      - ./bring-theme:/var/www/html/wp-content/themes/bring-theme

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  nginx:
    image: nginx:alpine
    depends_on:
      - wordpress
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./wordpress:/var/www/html
      - ./bring-theme:/var/www/html/wp-content/themes/bring-theme

volumes:
  db_data:

networks:
  default:
    driver: bridge
