module.exports = {
	plugins: [
		"@prettier/plugin-php",
		"prettier-plugin-tailwindcss",
		"prettier-plugin-organize-imports",
		"prettier-plugin-pkg",
		"prettier-plugin-tailwindcss",
	],
	arrowParens: "always",
	bracketSameLine: false,
	bracketSpacing: true,
	endOfLine: "lf",
	htmlWhitespaceSensitivity: "css",
	jsxSingleQuote: false,
	printWidth: 100,
	proseWrap: "preserve",
	quoteProps: "as-needed",
	semi: false,
	singleQuote: false,
	tabWidth: 2,
	trailingComma: "es5",
	useTabs: true,

	phpVersion: "8.2",
	trailingCommaPHP: true,
	braceStyle: "1tbs",

	tailwindConfig: "./next-app/tailwind.config.ts",
	tailwindFunctions: ["twJoin", "twMerge"],
}
