name: Production CD

on:
  workflow_dispatch:
  push:
    branches:
      - production

jobs:
  deploy-production:
    uses: ./.github/workflows/cd.yml
    secrets: inherit
    with:
      environment: production
